### ISSUE TITLE
help

### ISSUE THREAD

**Issue by SwingLouis** [ZewanHuang/MiniApp#2]
请问可以发一下数据库吗

**Comment by huanngzh** [comment]
你好，可以在https://github.com/ZewanHuang/Order-Applet/tree/master/springboot/src/main/java/com/example/demo/bean 中看到各个entity是如何设计的，这些类的属性和数据库表属性是对应的，可以了解一下Springboot后端框架。

**Comment by SwingLouis** [comment]
好的，已经了解了，一开始没有仔细看后端的代码，我想看一下你的代码设计文档，但是打不开啊
![image](https://user-images.githubusercontent.com/115707363/202343680-4268d8c2-ed1e-4759-9a00-d848ef34b0b6.png)
